import {
  Property,
  Unit,
  Inspection,
  UnitTurn,
  MaintenanceRequest,
  DashboardStats,
} from "./types";

// --- Properties (USC off-campus housing) ---
export const properties: Property[] = [
  {
    id: "prop-1",
    name: "The Lorenzo",
    address: "325 W Adams Blvd, Los Angeles, CA 90007",
    unitCount: 24,
  },
  {
    id: "prop-2",
    name: "Cardinal Gardens",
    address: "2707 S Hoover St, Los Angeles, CA 90007",
    unitCount: 18,
  },
  {
    id: "prop-3",
    name: "Troy Hall",
    address: "1050 W 30th St, Los Angeles, CA 90007",
    unitCount: 32,
  },
];

export const units: Unit[] = [
  { id: "unit-1", propertyId: "prop-1", number: "101", bedrooms: 2, bathrooms: 1, sqft: 850, status: "occupied", currentTenantId: "t-1" },
  { id: "unit-2", propertyId: "prop-1", number: "102", bedrooms: 1, bathrooms: 1, sqft: 600, status: "turning" },
  { id: "unit-3", propertyId: "prop-1", number: "201", bedrooms: 3, bathrooms: 2, sqft: 1100, status: "occupied", currentTenantId: "t-2" },
  { id: "unit-4", propertyId: "prop-2", number: "A1", bedrooms: 2, bathrooms: 1, sqft: 800, status: "vacant" },
  { id: "unit-5", propertyId: "prop-2", number: "B3", bedrooms: 4, bathrooms: 2, sqft: 1400, status: "occupied", currentTenantId: "t-3" },
  { id: "unit-6", propertyId: "prop-3", number: "301", bedrooms: 2, bathrooms: 2, sqft: 950, status: "occupied", currentTenantId: "t-4" },
  { id: "unit-7", propertyId: "prop-3", number: "105", bedrooms: 1, bathrooms: 1, sqft: 550, status: "turning" },
];

// --- Inspections ---
export const inspections: Inspection[] = [
  {
    id: "insp-1",
    unitId: "unit-2",
    propertyId: "prop-1",
    unitNumber: "102",
    propertyName: "The Lorenzo",
    type: "move_out",
    status: "scheduled",
    scheduledDate: "2026-03-05",
    inspector: "Carlos R.",
    items: [],
    overallNotes: "",
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "insp-2",
    unitId: "unit-4",
    propertyId: "prop-2",
    unitNumber: "A1",
    propertyName: "Cardinal Gardens",
    type: "move_in",
    status: "completed",
    scheduledDate: "2026-02-20",
    completedDate: "2026-02-20",
    inspector: "Maria L.",
    items: [
      { id: "item-1", area: "Kitchen", item: "Countertops", condition: "good", notes: "Minor scratch near sink", photos: [] },
      { id: "item-2", area: "Kitchen", item: "Appliances", condition: "excellent", notes: "All working", photos: [] },
      { id: "item-3", area: "Bathroom", item: "Fixtures", condition: "good", notes: "", photos: [] },
      { id: "item-4", area: "Living Room", item: "Flooring", condition: "fair", notes: "Some wear near entry", photos: [] },
      { id: "item-5", area: "Bedroom", item: "Walls", condition: "good", notes: "Small nail holes patched", photos: [] },
    ],
    overallNotes: "Unit in good condition overall. Ready for new tenant.",
    createdAt: "2026-02-18T08:00:00Z",
    updatedAt: "2026-02-20T16:30:00Z",
  },
  {
    id: "insp-3",
    unitId: "unit-6",
    propertyId: "prop-3",
    unitNumber: "301",
    propertyName: "Troy Hall",
    type: "quarterly",
    status: "in_progress",
    scheduledDate: "2026-02-27",
    inspector: "Carlos R.",
    items: [
      { id: "item-6", area: "Kitchen", item: "Smoke Detector", condition: "excellent", notes: "Battery replaced", photos: [] },
      { id: "item-7", area: "Bathroom", item: "Plumbing", condition: "fair", notes: "Slow drain — needs attention", photos: [] },
    ],
    overallNotes: "In progress — bathroom drain flagged for maintenance.",
    createdAt: "2026-02-26T09:00:00Z",
    updatedAt: "2026-02-27T11:00:00Z",
  },
];

// --- Unit Turns ---
export const unitTurns: UnitTurn[] = [
  {
    id: "turn-1",
    unitId: "unit-2",
    propertyId: "prop-1",
    unitNumber: "102",
    propertyName: "The Lorenzo",
    moveOutDate: "2026-03-01",
    targetReadyDate: "2026-03-15",
    moveInDate: "2026-03-20",
    status: "pending",
    outgoingTenant: "Jake M.",
    incomingTenant: "Sarah K.",
    tasks: [
      { id: "tt-1", name: "Deep clean entire unit", category: "cleaning", status: "not_started", estimatedCost: 350, actualCost: undefined, notes: "", dueDate: "2026-03-03" },
      { id: "tt-2", name: "Paint walls — bedroom & living room", category: "paint", status: "not_started", vendor: "QuickPaint LA", estimatedCost: 600, actualCost: undefined, notes: "Match existing color SW 7015", dueDate: "2026-03-06" },
      { id: "tt-3", name: "Replace kitchen faucet", category: "repairs", status: "not_started", estimatedCost: 180, actualCost: undefined, notes: "Tenant reported drip", dueDate: "2026-03-05" },
      { id: "tt-4", name: "Steam clean carpets", category: "flooring", status: "not_started", vendor: "Stanley Steemer", estimatedCost: 200, actualCost: undefined, notes: "", dueDate: "2026-03-08" },
      { id: "tt-5", name: "Final walkthrough", category: "final_walk", status: "not_started", assignedTo: "Carlos R.", estimatedCost: 0, actualCost: undefined, notes: "", dueDate: "2026-03-14" },
    ],
    totalBudget: 1500,
    totalSpent: 0,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "turn-2",
    unitId: "unit-7",
    propertyId: "prop-3",
    unitNumber: "105",
    propertyName: "Troy Hall",
    moveOutDate: "2026-02-15",
    targetReadyDate: "2026-03-01",
    status: "in_progress",
    outgoingTenant: "Chris D.",
    tasks: [
      { id: "tt-6", name: "Deep clean entire unit", category: "cleaning", status: "completed", estimatedCost: 250, actualCost: 250, notes: "", completedDate: "2026-02-18" },
      { id: "tt-7", name: "Patch and paint all walls", category: "paint", status: "completed", vendor: "QuickPaint LA", estimatedCost: 400, actualCost: 425, notes: "Extra patching needed in bedroom", completedDate: "2026-02-22" },
      { id: "tt-8", name: "Replace bathroom vanity", category: "repairs", status: "in_progress", vendor: "Home Depot Install", estimatedCost: 550, actualCost: undefined, notes: "Vanity ordered, awaiting delivery", dueDate: "2026-02-28" },
      { id: "tt-9", name: "Final walkthrough", category: "final_walk", status: "not_started", assignedTo: "Maria L.", estimatedCost: 0, actualCost: undefined, notes: "", dueDate: "2026-03-01" },
    ],
    totalBudget: 1300,
    totalSpent: 675,
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-27T10:00:00Z",
  },
];

// --- Maintenance Requests ---
export const maintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint-1",
    unitId: "unit-1",
    propertyId: "prop-1",
    unitNumber: "101",
    propertyName: "The Lorenzo",
    tenantName: "Alex T.",
    tenantPhone: "(213) 555-0142",
    category: "plumbing",
    priority: "high",
    status: "assigned",
    title: "Kitchen sink leaking under cabinet",
    description: "Water pooling under kitchen sink cabinet. Started yesterday. Bucket placed to catch drip.",
    photos: [],
    assignedTo: "Carlos R.",
    vendor: "Roto-Rooter",
    scheduledDate: "2026-02-28",
    notes: ["Tenant notified of scheduled repair date."],
    createdAt: "2026-02-26T18:00:00Z",
    updatedAt: "2026-02-27T09:00:00Z",
  },
  {
    id: "maint-2",
    unitId: "unit-5",
    propertyId: "prop-2",
    unitNumber: "B3",
    propertyName: "Cardinal Gardens",
    tenantName: "Jordan P.",
    tenantEmail: "jordan.p@usc.edu",
    category: "hvac",
    priority: "medium",
    status: "submitted",
    title: "AC not cooling properly",
    description: "Unit not reaching set temperature. Currently 78°F when set to 72°F. Filter was recently changed.",
    photos: [],
    notes: [],
    createdAt: "2026-02-27T08:30:00Z",
    updatedAt: "2026-02-27T08:30:00Z",
  },
  {
    id: "maint-3",
    unitId: "unit-3",
    propertyId: "prop-1",
    unitNumber: "201",
    propertyName: "The Lorenzo",
    tenantName: "Priya S.",
    tenantPhone: "(213) 555-0198",
    category: "locksmith",
    priority: "emergency",
    status: "in_progress",
    title: "Locked out — front door lock jammed",
    description: "Tenant locked out. Key turns but deadbolt won't retract. Locksmith en route.",
    photos: [],
    assignedTo: "Carlos R.",
    vendor: "Pop-A-Lock LA",
    notes: ["Emergency call placed. Locksmith ETA 30 min.", "Tenant waiting in lobby."],
    createdAt: "2026-02-27T14:00:00Z",
    updatedAt: "2026-02-27T14:20:00Z",
  },
  {
    id: "maint-4",
    unitId: "unit-6",
    propertyId: "prop-3",
    unitNumber: "301",
    propertyName: "Troy Hall",
    tenantName: "Marcus W.",
    category: "appliance",
    priority: "low",
    status: "completed",
    title: "Dishwasher not draining fully",
    description: "Small amount of water remaining after cycle. Cleaned filter but issue persists.",
    photos: [],
    assignedTo: "Maria L.",
    actualCost: 0,
    completedDate: "2026-02-25",
    notes: ["Cleared drain hose blockage. No parts needed.", "Tenant confirmed working properly."],
    createdAt: "2026-02-22T11:00:00Z",
    updatedAt: "2026-02-25T15:00:00Z",
  },
];

// --- Dashboard Stats ---
export const dashboardStats: DashboardStats = {
  totalUnits: 74,
  occupiedUnits: 65,
  vacantUnits: 4,
  turningUnits: 5,
  activeInspections: 2,
  openMaintenanceRequests: 3,
  upcomingTurns: 2,
};
