import {
  Property,
  Unit,
  Inspection,
  UnitTurn,
  MaintenanceRequest,
  DashboardStats,
  ApplicationGroup,
  Applicant,
  ApplicantStep,
  DocumentUpload,
  TourSlot,
  UserRole,
  AppCategory,
  AppConfig,
  AppCategoryConfig,
} from "./types";

// --- Properties (USC off-campus housing) ---
export const properties: Property[] = [
  {
    id: "prop-1",
    name: "The Lorenzo",
    address: "325 W Adams Blvd, Los Angeles, CA 90007",
    unitCount: 24,
  },
  {
    id: "prop-2",
    name: "Cardinal Gardens",
    address: "2707 S Hoover St, Los Angeles, CA 90007",
    unitCount: 18,
  },
  {
    id: "prop-3",
    name: "Troy Hall",
    address: "1050 W 30th St, Los Angeles, CA 90007",
    unitCount: 32,
  },
];

export const units: Unit[] = [
  { id: "unit-1", propertyId: "prop-1", number: "101", bedrooms: 2, bathrooms: 1, sqft: 850, status: "occupied", currentTenantId: "t-1" },
  { id: "unit-2", propertyId: "prop-1", number: "102", bedrooms: 1, bathrooms: 1, sqft: 600, status: "turning" },
  { id: "unit-3", propertyId: "prop-1", number: "201", bedrooms: 3, bathrooms: 2, sqft: 1100, status: "occupied", currentTenantId: "t-2" },
  { id: "unit-4", propertyId: "prop-2", number: "A1", bedrooms: 2, bathrooms: 1, sqft: 800, status: "vacant" },
  { id: "unit-5", propertyId: "prop-2", number: "B3", bedrooms: 4, bathrooms: 2, sqft: 1400, status: "occupied", currentTenantId: "t-3" },
  { id: "unit-6", propertyId: "prop-3", number: "301", bedrooms: 2, bathrooms: 2, sqft: 950, status: "occupied", currentTenantId: "t-4" },
  { id: "unit-7", propertyId: "prop-3", number: "105", bedrooms: 1, bathrooms: 1, sqft: 550, status: "turning" },
];

// --- Inspections ---
export const inspections: Inspection[] = [
  {
    id: "insp-1",
    unitId: "unit-2",
    propertyId: "prop-1",
    unitNumber: "102",
    propertyName: "The Lorenzo",
    type: "move_out",
    status: "scheduled",
    scheduledDate: "2026-03-05",
    inspector: "Carlos R.",
    items: [],
    overallNotes: "",
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "insp-2",
    unitId: "unit-4",
    propertyId: "prop-2",
    unitNumber: "A1",
    propertyName: "Cardinal Gardens",
    type: "move_in",
    status: "completed",
    scheduledDate: "2026-02-20",
    completedDate: "2026-02-20",
    inspector: "Maria L.",
    items: [
      { id: "item-1", area: "Kitchen", item: "Countertops", condition: "good", notes: "Minor scratch near sink", photos: [] },
      { id: "item-2", area: "Kitchen", item: "Appliances", condition: "excellent", notes: "All working", photos: [] },
      { id: "item-3", area: "Bathroom", item: "Fixtures", condition: "good", notes: "", photos: [] },
      { id: "item-4", area: "Living Room", item: "Flooring", condition: "fair", notes: "Some wear near entry", photos: [] },
      { id: "item-5", area: "Bedroom", item: "Walls", condition: "good", notes: "Small nail holes patched", photos: [] },
    ],
    overallNotes: "Unit in good condition overall. Ready for new tenant.",
    createdAt: "2026-02-18T08:00:00Z",
    updatedAt: "2026-02-20T16:30:00Z",
  },
  {
    id: "insp-3",
    unitId: "unit-6",
    propertyId: "prop-3",
    unitNumber: "301",
    propertyName: "Troy Hall",
    type: "quarterly",
    status: "in_progress",
    scheduledDate: "2026-02-27",
    inspector: "Carlos R.",
    items: [
      { id: "item-6", area: "Kitchen", item: "Smoke Detector", condition: "excellent", notes: "Battery replaced", photos: [] },
      { id: "item-7", area: "Bathroom", item: "Plumbing", condition: "fair", notes: "Slow drain — needs attention", photos: [] },
    ],
    overallNotes: "In progress — bathroom drain flagged for maintenance.",
    createdAt: "2026-02-26T09:00:00Z",
    updatedAt: "2026-02-27T11:00:00Z",
  },
];

// --- Unit Turns ---
export const unitTurns: UnitTurn[] = [
  {
    id: "turn-1",
    unitId: "unit-2",
    propertyId: "prop-1",
    unitNumber: "102",
    propertyName: "The Lorenzo",
    moveOutDate: "2026-03-01",
    targetReadyDate: "2026-03-15",
    moveInDate: "2026-03-20",
    status: "pending",
    outgoingTenant: "Jake M.",
    incomingTenant: "Sarah K.",
    tasks: [
      { id: "tt-1", name: "Deep clean entire unit", category: "cleaning", status: "not_started", estimatedCost: 350, actualCost: undefined, notes: "", dueDate: "2026-03-03" },
      { id: "tt-2", name: "Paint walls — bedroom & living room", category: "paint", status: "not_started", vendor: "QuickPaint LA", estimatedCost: 600, actualCost: undefined, notes: "Match existing color SW 7015", dueDate: "2026-03-06" },
      { id: "tt-3", name: "Replace kitchen faucet", category: "repairs", status: "not_started", estimatedCost: 180, actualCost: undefined, notes: "Tenant reported drip", dueDate: "2026-03-05" },
      { id: "tt-4", name: "Steam clean carpets", category: "flooring", status: "not_started", vendor: "Stanley Steemer", estimatedCost: 200, actualCost: undefined, notes: "", dueDate: "2026-03-08" },
      { id: "tt-5", name: "Final walkthrough", category: "final_walk", status: "not_started", assignedTo: "Carlos R.", estimatedCost: 0, actualCost: undefined, notes: "", dueDate: "2026-03-14" },
    ],
    totalBudget: 1500,
    totalSpent: 0,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "turn-2",
    unitId: "unit-7",
    propertyId: "prop-3",
    unitNumber: "105",
    propertyName: "Troy Hall",
    moveOutDate: "2026-02-15",
    targetReadyDate: "2026-03-01",
    status: "in_progress",
    outgoingTenant: "Chris D.",
    tasks: [
      { id: "tt-6", name: "Deep clean entire unit", category: "cleaning", status: "completed", estimatedCost: 250, actualCost: 250, notes: "", completedDate: "2026-02-18" },
      { id: "tt-7", name: "Patch and paint all walls", category: "paint", status: "completed", vendor: "QuickPaint LA", estimatedCost: 400, actualCost: 425, notes: "Extra patching needed in bedroom", completedDate: "2026-02-22" },
      { id: "tt-8", name: "Replace bathroom vanity", category: "repairs", status: "in_progress", vendor: "Home Depot Install", estimatedCost: 550, actualCost: undefined, notes: "Vanity ordered, awaiting delivery", dueDate: "2026-02-28" },
      { id: "tt-9", name: "Final walkthrough", category: "final_walk", status: "not_started", assignedTo: "Maria L.", estimatedCost: 0, actualCost: undefined, notes: "", dueDate: "2026-03-01" },
    ],
    totalBudget: 1300,
    totalSpent: 675,
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-27T10:00:00Z",
  },
];

// --- Maintenance Requests ---
export const maintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint-1",
    unitId: "unit-1",
    propertyId: "prop-1",
    unitNumber: "101",
    propertyName: "The Lorenzo",
    tenantName: "Alex T.",
    tenantPhone: "(213) 555-0142",
    category: "plumbing",
    priority: "high",
    status: "assigned",
    title: "Kitchen sink leaking under cabinet",
    description: "Water pooling under kitchen sink cabinet. Started yesterday. Bucket placed to catch drip.",
    photos: [],
    assignedTo: "Carlos R.",
    vendor: "Roto-Rooter",
    scheduledDate: "2026-02-28",
    notes: ["Tenant notified of scheduled repair date."],
    createdAt: "2026-02-26T18:00:00Z",
    updatedAt: "2026-02-27T09:00:00Z",
  },
  {
    id: "maint-2",
    unitId: "unit-5",
    propertyId: "prop-2",
    unitNumber: "B3",
    propertyName: "Cardinal Gardens",
    tenantName: "Jordan P.",
    tenantEmail: "jordan.p@usc.edu",
    category: "hvac",
    priority: "medium",
    status: "submitted",
    title: "AC not cooling properly",
    description: "Unit not reaching set temperature. Currently 78°F when set to 72°F. Filter was recently changed.",
    photos: [],
    notes: [],
    createdAt: "2026-02-27T08:30:00Z",
    updatedAt: "2026-02-27T08:30:00Z",
  },
  {
    id: "maint-3",
    unitId: "unit-3",
    propertyId: "prop-1",
    unitNumber: "201",
    propertyName: "The Lorenzo",
    tenantName: "Priya S.",
    tenantPhone: "(213) 555-0198",
    category: "locksmith",
    priority: "emergency",
    status: "in_progress",
    title: "Locked out — front door lock jammed",
    description: "Tenant locked out. Key turns but deadbolt won't retract. Locksmith en route.",
    photos: [],
    assignedTo: "Carlos R.",
    vendor: "Pop-A-Lock LA",
    notes: ["Emergency call placed. Locksmith ETA 30 min.", "Tenant waiting in lobby."],
    createdAt: "2026-02-27T14:00:00Z",
    updatedAt: "2026-02-27T14:20:00Z",
  },
  {
    id: "maint-4",
    unitId: "unit-6",
    propertyId: "prop-3",
    unitNumber: "301",
    propertyName: "Troy Hall",
    tenantName: "Marcus W.",
    category: "appliance",
    priority: "low",
    status: "completed",
    title: "Dishwasher not draining fully",
    description: "Small amount of water remaining after cycle. Cleaned filter but issue persists.",
    photos: [],
    assignedTo: "Maria L.",
    actualCost: 0,
    completedDate: "2026-02-25",
    notes: ["Cleared drain hose blockage. No parts needed.", "Tenant confirmed working properly."],
    createdAt: "2026-02-22T11:00:00Z",
    updatedAt: "2026-02-25T15:00:00Z",
  },
];

// --- Leasing: Helper to build applicant steps ---
function makeApplicantSteps(overrides: Partial<Record<string, "pending" | "complete" | "in_review">> = {}): ApplicantStep[] {
  const defaults: { id: string; name: string; description: string; required: boolean }[] = [
    { id: "step-1", name: "Personal Information", description: "Full name, date of birth, SSN, current address", required: true },
    { id: "step-2", name: "Government-Issued ID", description: "Upload a valid photo ID (driver's license, passport, state ID)", required: true },
    { id: "step-3", name: "Proof of Enrollment", description: "USC student ID or acceptance letter", required: true },
    { id: "step-4", name: "Proof of Income", description: "Pay stubs, bank statements, or scholarship letter. Not required if parental guarantee is provided.", required: false },
    { id: "step-5", name: "Guarantor Information", description: "Parent/guardian name, email, phone, and relationship", required: true },
    { id: "step-6", name: "Guarantor Documents", description: "Guarantor's ID and proof of income (uploaded by guarantor)", required: true },
    { id: "step-7", name: "Background & Credit Check Authorization", description: "Authorize background and credit screening", required: true },
    { id: "step-8", name: "Application Fee Payment", description: "$50 non-refundable application fee", required: true },
  ];
  return defaults.map((s) => ({
    ...s,
    status: overrides[s.id] || "pending",
    completedAt: overrides[s.id] === "complete" ? "2026-03-10T12:00:00Z" : undefined,
  }));
}

function makeGuarantorSteps(overrides: Partial<Record<string, "pending" | "complete" | "in_review">> = {}): ApplicantStep[] {
  const defaults = [
    { id: "gstep-1", name: "Personal Information", description: "Full name, address, date of birth, SSN", required: true },
    { id: "gstep-2", name: "Government-Issued ID", description: "Upload a valid photo ID", required: true },
    { id: "gstep-3", name: "Proof of Income", description: "Recent pay stubs, tax return, or bank statements showing 3x rent", required: true },
    { id: "gstep-4", name: "Guarantor Agreement", description: "Sign the parental guarantee form", required: true },
    { id: "gstep-5", name: "Background & Credit Check", description: "Authorize background and credit screening", required: true },
  ];
  return defaults.map((s) => ({
    ...s,
    status: overrides[s.id] || "pending",
    completedAt: overrides[s.id] === "complete" ? "2026-03-09T15:00:00Z" : undefined,
  }));
}

function makeDocs(role: "applicant" | "guarantor", uploaded: string[] = []): DocumentUpload[] {
  if (role === "applicant") {
    return [
      { id: "doc-id", type: "government_id", label: "Government ID", fileName: uploaded.includes("government_id") ? "drivers_license.jpg" : undefined, uploadedAt: uploaded.includes("government_id") ? "2026-03-08T10:00:00Z" : undefined, status: uploaded.includes("government_id") ? "verified" : "missing" },
      { id: "doc-enroll", type: "proof_of_enrollment", label: "Proof of Enrollment", fileName: uploaded.includes("proof_of_enrollment") ? "usc_student_id.pdf" : undefined, uploadedAt: uploaded.includes("proof_of_enrollment") ? "2026-03-08T10:05:00Z" : undefined, status: uploaded.includes("proof_of_enrollment") ? "uploaded" : "missing" },
      { id: "doc-income", type: "proof_of_income", label: "Proof of Income (optional if guarantor)", fileName: uploaded.includes("proof_of_income") ? "bank_statement.pdf" : undefined, uploadedAt: uploaded.includes("proof_of_income") ? "2026-03-09T08:00:00Z" : undefined, status: uploaded.includes("proof_of_income") ? "uploaded" : "missing" },
    ];
  }
  return [
    { id: "gdoc-id", type: "government_id", label: "Guarantor ID", fileName: uploaded.includes("government_id") ? "parent_id.jpg" : undefined, uploadedAt: uploaded.includes("government_id") ? "2026-03-09T14:00:00Z" : undefined, status: uploaded.includes("government_id") ? "verified" : "missing" },
    { id: "gdoc-income", type: "proof_of_income", label: "Guarantor Proof of Income", fileName: uploaded.includes("proof_of_income") ? "tax_return_2025.pdf" : undefined, uploadedAt: uploaded.includes("proof_of_income") ? "2026-03-09T14:10:00Z" : undefined, status: uploaded.includes("proof_of_income") ? "uploaded" : "missing" },
    { id: "gdoc-form", type: "guarantor_form", label: "Signed Guarantee Agreement", fileName: uploaded.includes("guarantor_form") ? "guarantee_signed.pdf" : undefined, uploadedAt: uploaded.includes("guarantor_form") ? "2026-03-09T14:15:00Z" : undefined, status: uploaded.includes("guarantor_form") ? "uploaded" : "missing" },
  ];
}

// --- Application Groups ---
export const applicationGroups: ApplicationGroup[] = [
  {
    id: "app-1",
    propertyId: "prop-1",
    propertyName: "The Lorenzo",
    unitNumber: "201",
    unitDetails: "3BR / 2BA · 1,100 sqft",
    leaseCycle: "fall_2026",
    targetMoveIn: "2026-08-15",
    monthlyRent: 3600,
    status: "incomplete",
    createdAt: "2026-03-05T09:00:00Z",
    updatedAt: "2026-03-13T16:00:00Z",
    applicants: [
      {
        id: "appl-1",
        groupId: "app-1",
        name: "Sarah Kim",
        email: "sarah.kim@usc.edu",
        phone: "(213) 555-0301",
        role: "primary",
        steps: makeApplicantSteps({ "step-1": "complete", "step-2": "complete", "step-3": "complete", "step-5": "complete", "step-7": "complete", "step-8": "complete" }),
        documents: makeDocs("applicant", ["government_id", "proof_of_enrollment"]),
        nudges: [
          { id: "n-1", channel: "email", message: "Hi Sarah, your application for The Lorenzo #201 is 75% complete. Upload your remaining documents to finalize.", scheduledAt: "2026-03-10T09:00:00Z", sentAt: "2026-03-10T09:00:00Z", status: "opened" },
          { id: "n-2", channel: "sms", message: "Reminder: Complete your Moxie application — guarantor docs still needed.", scheduledAt: "2026-03-12T09:00:00Z", sentAt: "2026-03-12T09:01:00Z", status: "delivered" },
        ],
        status: "in_progress",
        startedAt: "2026-03-05T09:30:00Z",
      },
      {
        id: "appl-2",
        groupId: "app-1",
        name: "Jake Martinez",
        email: "jake.m@usc.edu",
        phone: "(213) 555-0302",
        role: "co_applicant",
        steps: makeApplicantSteps({ "step-1": "complete", "step-2": "complete", "step-3": "complete", "step-5": "complete", "step-8": "complete" }),
        documents: makeDocs("applicant", ["government_id", "proof_of_enrollment"]),
        nudges: [
          { id: "n-3", channel: "email", message: "Hi Jake, your roommate Sarah has started the application. Complete your steps to secure The Lorenzo #201.", scheduledAt: "2026-03-06T09:00:00Z", sentAt: "2026-03-06T09:00:00Z", status: "opened" },
        ],
        status: "in_progress",
        startedAt: "2026-03-06T10:00:00Z",
      },
      {
        id: "appl-3",
        groupId: "app-1",
        name: "Ryan Lee",
        email: "ryan.lee@usc.edu",
        role: "co_applicant",
        steps: makeApplicantSteps({ "step-1": "complete", "step-8": "complete" }),
        documents: makeDocs("applicant", []),
        nudges: [
          { id: "n-4", channel: "email", message: "Hi Ryan, your roommates have started the application for The Lorenzo #201. Get started now!", scheduledAt: "2026-03-06T09:00:00Z", sentAt: "2026-03-06T09:00:00Z", status: "delivered" },
          { id: "n-5", channel: "email", message: "Ryan, your application is only 25% complete. You need to upload your ID and enrollment docs.", scheduledAt: "2026-03-09T09:00:00Z", sentAt: "2026-03-09T09:00:00Z", status: "delivered" },
          { id: "n-6", channel: "sms", message: "URGENT: Ryan, your roommates are waiting on you. Complete your Moxie application today.", scheduledAt: "2026-03-12T09:00:00Z", sentAt: "2026-03-12T09:01:00Z", status: "sent" },
        ],
        status: "in_progress",
        startedAt: "2026-03-07T14:00:00Z",
      },
      {
        id: "appl-4",
        groupId: "app-1",
        name: "Linda Kim",
        email: "linda.kim@gmail.com",
        phone: "(562) 555-0401",
        role: "guarantor",
        guarantorFor: "appl-1",
        steps: makeGuarantorSteps({ "gstep-1": "complete", "gstep-2": "complete", "gstep-3": "complete", "gstep-4": "complete", "gstep-5": "complete" }),
        documents: makeDocs("guarantor", ["government_id", "proof_of_income", "guarantor_form"]),
        nudges: [],
        status: "complete",
        startedAt: "2026-03-07T11:00:00Z",
        completedAt: "2026-03-09T15:00:00Z",
      },
      {
        id: "appl-5",
        groupId: "app-1",
        name: "Tom Martinez",
        email: "tom.martinez@yahoo.com",
        phone: "(818) 555-0402",
        role: "guarantor",
        guarantorFor: "appl-2",
        steps: makeGuarantorSteps({ "gstep-1": "complete", "gstep-2": "complete", "gstep-3": "complete" }),
        documents: makeDocs("guarantor", ["government_id", "proof_of_income"]),
        nudges: [
          { id: "n-7", channel: "email", message: "Hi Tom, Jake has listed you as a guarantor. Please complete the guarantee agreement for The Lorenzo #201.", scheduledAt: "2026-03-08T09:00:00Z", sentAt: "2026-03-08T09:00:00Z", status: "opened" },
        ],
        status: "in_progress",
        startedAt: "2026-03-08T10:00:00Z",
      },
      {
        id: "appl-6",
        groupId: "app-1",
        name: "Ryan's Guarantor",
        email: "",
        role: "guarantor",
        guarantorFor: "appl-3",
        steps: makeGuarantorSteps(),
        documents: makeDocs("guarantor", []),
        nudges: [],
        status: "not_started",
      },
    ],
  },
  {
    id: "app-2",
    propertyId: "prop-2",
    propertyName: "Cardinal Gardens",
    unitNumber: "A1",
    unitDetails: "2BR / 1BA · 800 sqft",
    leaseCycle: "fall_2026",
    targetMoveIn: "2026-08-20",
    monthlyRent: 2400,
    status: "under_review",
    createdAt: "2026-02-28T14:00:00Z",
    updatedAt: "2026-03-12T10:00:00Z",
    applicants: [
      {
        id: "appl-7",
        groupId: "app-2",
        name: "Mia Chen",
        email: "mia.chen@usc.edu",
        phone: "(213) 555-0310",
        role: "primary",
        steps: makeApplicantSteps({ "step-1": "complete", "step-2": "complete", "step-3": "complete", "step-4": "complete", "step-5": "complete", "step-6": "complete", "step-7": "complete", "step-8": "complete" }),
        documents: makeDocs("applicant", ["government_id", "proof_of_enrollment", "proof_of_income"]),
        nudges: [],
        status: "complete",
        startedAt: "2026-02-28T14:30:00Z",
        completedAt: "2026-03-05T11:00:00Z",
      },
      {
        id: "appl-8",
        groupId: "app-2",
        name: "Aisha Patel",
        email: "aisha.p@usc.edu",
        phone: "(213) 555-0311",
        role: "co_applicant",
        steps: makeApplicantSteps({ "step-1": "complete", "step-2": "complete", "step-3": "complete", "step-4": "complete", "step-5": "complete", "step-6": "complete", "step-7": "complete", "step-8": "complete" }),
        documents: makeDocs("applicant", ["government_id", "proof_of_enrollment", "proof_of_income"]),
        nudges: [],
        status: "complete",
        startedAt: "2026-03-01T09:00:00Z",
        completedAt: "2026-03-06T14:00:00Z",
      },
      {
        id: "appl-9",
        groupId: "app-2",
        name: "Wei Chen",
        email: "wei.chen@gmail.com",
        phone: "(626) 555-0501",
        role: "guarantor",
        guarantorFor: "appl-7",
        steps: makeGuarantorSteps({ "gstep-1": "complete", "gstep-2": "complete", "gstep-3": "complete", "gstep-4": "complete", "gstep-5": "complete" }),
        documents: makeDocs("guarantor", ["government_id", "proof_of_income", "guarantor_form"]),
        nudges: [],
        status: "complete",
        startedAt: "2026-03-02T08:00:00Z",
        completedAt: "2026-03-04T16:00:00Z",
      },
      {
        id: "appl-10",
        groupId: "app-2",
        name: "Raj Patel",
        email: "raj.patel@gmail.com",
        phone: "(714) 555-0502",
        role: "guarantor",
        guarantorFor: "appl-8",
        steps: makeGuarantorSteps({ "gstep-1": "complete", "gstep-2": "complete", "gstep-3": "complete", "gstep-4": "complete", "gstep-5": "complete" }),
        documents: makeDocs("guarantor", ["government_id", "proof_of_income", "guarantor_form"]),
        nudges: [],
        status: "complete",
        startedAt: "2026-03-03T10:00:00Z",
        completedAt: "2026-03-05T12:00:00Z",
      },
    ],
  },
  {
    id: "app-3",
    propertyId: "prop-3",
    propertyName: "Troy Hall",
    unitNumber: "301",
    unitDetails: "2BR / 2BA · 950 sqft",
    leaseCycle: "fall_2026",
    targetMoveIn: "2026-08-18",
    monthlyRent: 2800,
    status: "incomplete",
    createdAt: "2026-03-10T11:00:00Z",
    updatedAt: "2026-03-13T09:00:00Z",
    applicants: [
      {
        id: "appl-11",
        groupId: "app-3",
        name: "Jordan Williams",
        email: "jordan.w@usc.edu",
        phone: "(213) 555-0320",
        role: "primary",
        steps: makeApplicantSteps({ "step-1": "complete", "step-2": "complete", "step-3": "in_review" }),
        documents: makeDocs("applicant", ["government_id"]),
        nudges: [
          { id: "n-8", channel: "email", message: "Hi Jordan, we're reviewing your enrollment docs. In the meantime, please complete the remaining steps.", scheduledAt: "2026-03-12T09:00:00Z", sentAt: "2026-03-12T09:00:00Z", status: "opened" },
        ],
        status: "in_progress",
        startedAt: "2026-03-10T11:30:00Z",
      },
      {
        id: "appl-12",
        groupId: "app-3",
        name: "Taylor Brooks",
        email: "taylor.b@usc.edu",
        role: "co_applicant",
        steps: makeApplicantSteps({ "step-1": "complete" }),
        documents: makeDocs("applicant", []),
        nudges: [
          { id: "n-9", channel: "email", message: "Hi Taylor, Jordan has started your joint application for Troy Hall #301. Complete your application now.", scheduledAt: "2026-03-11T09:00:00Z", sentAt: "2026-03-11T09:00:00Z", status: "delivered" },
          { id: "n-10", channel: "sms", message: "Taylor — your Troy Hall application needs attention. Only 1 of 8 steps complete.", scheduledAt: "2026-03-13T09:00:00Z", status: "scheduled" },
        ],
        status: "in_progress",
        startedAt: "2026-03-11T15:00:00Z",
      },
    ],
  },
];

// --- Tour Slots ---
export const tourSlots: TourSlot[] = [
  {
    id: "tour-1",
    propertyId: "prop-1",
    propertyName: "The Lorenzo",
    date: "2026-03-21",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    host: "Maria L.",
    capacity: 10,
    registrations: [
      { id: "reg-1", prospectName: "Sarah Kim", prospectEmail: "sarah.kim@usc.edu", status: "attended", registeredAt: "2026-03-01T10:00:00Z", source: "USC Housing Board", followUpSent: true },
      { id: "reg-2", prospectName: "Jake Martinez", prospectEmail: "jake.m@usc.edu", status: "attended", registeredAt: "2026-03-01T14:00:00Z", source: "Referral (Sarah Kim)", followUpSent: true },
      { id: "reg-3", prospectName: "Ryan Lee", prospectEmail: "ryan.lee@usc.edu", status: "no_show", registeredAt: "2026-03-02T09:00:00Z", source: "Apartments.com", followUpSent: true },
      { id: "reg-4", prospectName: "Emma Davis", prospectEmail: "emma.d@usc.edu", status: "attended", registeredAt: "2026-03-03T11:00:00Z", source: "Website" },
    ],
    preReminderStatus: "sent",
    postFollowUpStatus: "sent",
    notes: "Good turnout. 3 of 4 attended. Ryan was a no-show — follow-up sent to reschedule.",
    createdAt: "2026-02-25T09:00:00Z",
  },
  {
    id: "tour-2",
    propertyId: "prop-2",
    propertyName: "Cardinal Gardens",
    date: "2026-03-22",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    host: "Carlos R.",
    capacity: 8,
    registrations: [
      { id: "reg-5", prospectName: "Mia Chen", prospectEmail: "mia.chen@usc.edu", status: "confirmed", registeredAt: "2026-03-10T08:00:00Z", source: "Zillow" },
      { id: "reg-6", prospectName: "Aisha Patel", prospectEmail: "aisha.p@usc.edu", status: "confirmed", registeredAt: "2026-03-10T09:30:00Z", source: "Referral (Mia Chen)" },
      { id: "reg-7", prospectName: "Devon Park", prospectEmail: "devon.p@usc.edu", status: "pending", registeredAt: "2026-03-12T16:00:00Z", source: "Social Media" },
    ],
    preReminderStatus: "scheduled",
    postFollowUpStatus: "not_set",
    notes: "",
    createdAt: "2026-03-05T10:00:00Z",
  },
  {
    id: "tour-3",
    propertyId: "prop-3",
    propertyName: "Troy Hall",
    date: "2026-03-29",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    host: "Maria L.",
    capacity: 12,
    registrations: [
      { id: "reg-8", prospectName: "Jordan Williams", prospectEmail: "jordan.w@usc.edu", status: "confirmed", registeredAt: "2026-03-08T10:00:00Z", source: "Website" },
      { id: "reg-9", prospectName: "Taylor Brooks", prospectEmail: "taylor.b@usc.edu", status: "confirmed", registeredAt: "2026-03-08T10:15:00Z", source: "Referral (Jordan)" },
      { id: "reg-10", prospectName: "Kai Nguyen", prospectEmail: "kai.n@usc.edu", status: "confirmed", registeredAt: "2026-03-09T14:00:00Z", source: "USC Housing Board" },
      { id: "reg-11", prospectName: "Nina Rodriguez", prospectEmail: "nina.r@usc.edu", status: "pending", registeredAt: "2026-03-13T08:00:00Z", source: "Apartments.com" },
      { id: "reg-12", prospectName: "Sam Johnson", prospectEmail: "sam.j@usc.edu", status: "pending", registeredAt: "2026-03-13T11:00:00Z", source: "Walk-in" },
    ],
    preReminderStatus: "scheduled",
    postFollowUpStatus: "not_set",
    notes: "Large group expected. Prepare 2BR and studio units for showing.",
    createdAt: "2026-03-06T09:00:00Z",
  },
  {
    id: "tour-4",
    propertyId: "prop-1",
    propertyName: "The Lorenzo",
    date: "2026-04-05",
    startTime: "1:00 PM",
    endTime: "3:00 PM",
    host: "Carlos R.",
    capacity: 10,
    registrations: [],
    preReminderStatus: "not_set",
    postFollowUpStatus: "not_set",
    notes: "April open house — marketing push starting March 25.",
    createdAt: "2026-03-12T11:00:00Z",
  },
];

// --- Dashboard Stats ---
export const dashboardStats: DashboardStats = {
  totalUnits: 74,
  occupiedUnits: 65,
  vacantUnits: 4,
  turningUnits: 5,
  preLeasedUnits: 0,
  activeInspections: 2,
  openMaintenanceRequests: 3,
  upcomingTurns: 2,
  activeApplications: 3,
  upcomingTours: 3,
  upcomingMoveOuts: 4,
  vendorCount: 12,
  pendingRubs: "March pending",
  reportsDue: 2,
  activeCapitalProjects: 1,
  pendingNotices: 2,
  trackedComps: 3,
  recurringIssues: 2,
};

// --- App Launcher Configuration ---
export const appCategories: AppCategoryConfig[] = [
  { id: "operations", label: "Operations", color: "blue", order: 1 },
  { id: "leasing", label: "Leasing", color: "purple", order: 2 },
  { id: "finance", label: "Finance", color: "emerald", order: 3 },
  { id: "asset_management", label: "Asset Management", color: "amber", order: 4 },
  { id: "communications", label: "Communications", color: "rose", order: 5 },
];

export const apps: AppConfig[] = [
  // --- Operations ---
  {
    id: "inspections",
    name: "Inspections",
    description: "Move-in, move-out, and quarterly inspections with condition tracking and photos",
    href: "/inspections",
    icon: "ClipboardCheck",
    category: "operations",
    categoryLabel: "Operations",
    categoryColor: "blue",
    roles: ["property_manager", "maintenance_tech"],
    isBuilt: true,
    statLabel: `${dashboardStats.activeInspections} active`,
  },
  {
    id: "unit-turns",
    name: "Unit Turns",
    description: "Manage the full move-out to move-in workflow — cleaning, paint, repairs, walkthroughs",
    href: "/unit-turns",
    icon: "RefreshCw",
    category: "operations",
    categoryLabel: "Operations",
    categoryColor: "blue",
    roles: ["property_manager", "maintenance_tech"],
    isBuilt: true,
    statLabel: `${dashboardStats.upcomingTurns} in progress`,
  },
  {
    id: "maintenance",
    name: "Maintenance",
    description: "Track work orders from submission through completion. Assign vendors and monitor costs",
    href: "/maintenance",
    icon: "Wrench",
    category: "operations",
    categoryLabel: "Operations",
    categoryColor: "blue",
    roles: ["property_manager", "maintenance_tech"],
    isBuilt: true,
    statLabel: `${dashboardStats.openMaintenanceRequests} open`,
  },
  {
    id: "move-in-out",
    name: "Move In / Move Out",
    description: "Tenant-facing checklist for move day: key handoff, utility setup, welcome packet, condition photos",
    href: "/move-in-out",
    icon: "Truck",
    category: "operations",
    categoryLabel: "Operations",
    categoryColor: "blue",
    roles: ["property_manager", "maintenance_tech", "leasing_agent"],
    isBuilt: false,
    statLabel: `${dashboardStats.upcomingMoveOuts} upcoming`,
  },
  {
    id: "vendors",
    name: "Vendor Directory",
    description: "Preferred vendors, performance tracking, insurance status, and contact info. Synced with Notion",
    href: "/vendors",
    icon: "Users",
    category: "operations",
    categoryLabel: "Operations",
    categoryColor: "blue",
    roles: ["property_manager", "maintenance_tech"],
    isBuilt: false,
    statLabel: `${dashboardStats.vendorCount} vendors`,
  },
  // --- Leasing ---
  {
    id: "applications",
    name: "Applications",
    description: "Track lease applications, co-applicant progress, document uploads, guarantor status",
    href: "/leasing/applications",
    icon: "FileText",
    category: "leasing",
    categoryLabel: "Leasing",
    categoryColor: "purple",
    roles: ["property_manager", "leasing_agent"],
    isBuilt: true,
    statLabel: `${dashboardStats.activeApplications} active`,
  },
  {
    id: "tours",
    name: "Tour Scheduling",
    description: "Manage open house tours with automated reminders and post-tour follow-ups",
    href: "/leasing/tours",
    icon: "Calendar",
    category: "leasing",
    categoryLabel: "Leasing",
    categoryColor: "purple",
    roles: ["property_manager", "leasing_agent"],
    isBuilt: true,
    statLabel: `${dashboardStats.upcomingTours} upcoming`,
  },
  {
    id: "comp-watch",
    name: "Comp Watch",
    description: "Track competitor rents near USC — price drops, concessions, and demand signals during leasing season",
    href: "/comp-watch",
    icon: "TrendingUp",
    category: "leasing",
    categoryLabel: "Leasing",
    categoryColor: "purple",
    roles: ["property_manager", "leasing_agent", "asset_manager", "owner"],
    isBuilt: false,
    statLabel: `${dashboardStats.trackedComps} comps tracked`,
  },
  // --- Finance ---
  {
    id: "rubs",
    name: "RUBs",
    description: "Ratio Utility Billing — split water, gas, electric, and trash costs across tenants by sqft or occupancy",
    href: "/rubs",
    icon: "Zap",
    category: "finance",
    categoryLabel: "Finance",
    categoryColor: "emerald",
    roles: ["property_manager", "asset_manager", "owner"],
    isBuilt: false,
    statLabel: dashboardStats.pendingRubs,
  },
  {
    id: "reports",
    name: "Monthly Reports",
    description: "Generate and review monthly P&L, occupancy, and maintenance cost reports per property",
    href: "/reports",
    icon: "BarChart3",
    category: "finance",
    categoryLabel: "Finance",
    categoryColor: "emerald",
    roles: ["property_manager", "asset_manager", "owner"],
    isBuilt: false,
    statLabel: `${dashboardStats.reportsDue} reports due`,
  },
  // --- Asset Management ---
  {
    id: "portfolio",
    name: "Portfolio Overview",
    description: "Property-level performance dashboard: occupancy, revenue, expense ratios, and NOI per property",
    href: "/portfolio",
    icon: "Building2",
    category: "asset_management",
    categoryLabel: "Asset Management",
    categoryColor: "amber",
    roles: ["property_manager", "asset_manager", "owner"],
    isBuilt: false,
    statLabel: "3 properties",
  },
  {
    id: "capital-projects",
    name: "Capital Projects",
    description: "Track large improvements: roof replacements, HVAC upgrades, renovations with budget vs actual",
    href: "/capital-projects",
    icon: "HardHat",
    category: "asset_management",
    categoryLabel: "Asset Management",
    categoryColor: "amber",
    roles: ["property_manager", "asset_manager"],
    isBuilt: false,
    statLabel: `${dashboardStats.activeCapitalProjects} active`,
  },
  // --- Communications ---
  {
    id: "notices",
    name: "Tenant Notices",
    description: "Draft and send lease violation notices, rent reminders, and building-wide announcements",
    href: "/notices",
    icon: "Bell",
    category: "communications",
    categoryLabel: "Communications",
    categoryColor: "rose",
    roles: ["property_manager", "leasing_agent"],
    isBuilt: false,
    statLabel: `${dashboardStats.pendingNotices} pending`,
  },
  {
    id: "resident-pulse",
    name: "Resident Pulse",
    description: "Spot recurring issues from maintenance tickets, inspections, and reviews — surfaces the top problems each month",
    href: "/resident-pulse",
    icon: "MessageSquare",
    category: "communications",
    categoryLabel: "Communications",
    categoryColor: "rose",
    roles: ["property_manager", "leasing_agent", "asset_manager"],
    isBuilt: false,
    statLabel: `${dashboardStats.recurringIssues} recurring issues`,
  },
];

export const currentUserRole: UserRole = "property_manager";

export function getAppsForRole(role: UserRole): AppConfig[] {
  return apps.filter((app) => app.roles.includes(role));
}

export function getAppsByCategory(appList: AppConfig[]): Record<string, AppConfig[]> {
  const grouped: Record<string, AppConfig[]> = {};
  for (const app of appList) {
    if (!grouped[app.category]) grouped[app.category] = [];
    grouped[app.category].push(app);
  }
  return grouped;
}
