-- ============================================
-- Work Order Meeting Summaries (server-side cache)
-- ============================================
-- The Monday meeting view shows an AI-shortened headline for every
-- open work order so the team can scan the agenda. Today the headline
-- is generated by /api/maintenance/summarize and cached in the user's
-- localStorage — which means every fresh browser, every cleared cache,
-- and every new teammate triggers a re-generation against Claude.
--
-- This column moves that cache server-side so the AI call only ever
-- happens once per work order, and persists across users / devices.

alter table work_order_annotations
  add column if not exists meeting_summary text,
  add column if not exists meeting_summary_at timestamptz;

create index if not exists work_order_annotations_meeting_summary_at_idx
  on work_order_annotations (meeting_summary_at);
